<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>http_forwarder_acceptance_tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio"/>
    <PackageReference Include="Microsoft.AspNetCore.Testing"/>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
    <PackageReference Include="Shouldly"/>
    <PackageReference Include="Moq"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../http-forwarder-app/http-forwarder-app.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit"/>
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.test.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>