<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>http_forwarder_utils</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../http-forwarder-models/http-forwarder-models.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="*"/>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.*"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.*"/>
  </ItemGroup>
</Project>