name: Cleanup GHCR Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 * *' # Runs at 02:00 on the 1st day of every month

jobs:
  cleanup:
    name: Cleanup old container images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Apply container retention policy
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: http-forwarder-app
          image-tags: "!latest"
          cut-off: 90d
          keep-n-most-recent: 10
          dry-run: true
